import type { SurveyQuestion, SurveySection } from './types';

const opt = (label: string) => ({ label, value: label });

export const questions: SurveyQuestion[] = [
  // Section 1: Questions about your Immich server, your library and your internet speed
  {
    id: 'q1',
    section: 1,
    sectionTitle: 'Questions about your Immich server, your library and your internet speed',
    text: 'Where is your Immich server located?',
    type: 'radio',
    required: true,
    hasOther: true,
    otherPrompt: 'Please enter where your Immich server is located',
    options: [
      opt('North America - East (US East Coast, Eastern Canada)'),
      opt('North America - Central (US Midwest, Central Canada)'),
      opt('North America - West (US West Coast, Western Canada)'),
      opt('South America'),
      opt('Europe - West (UK, France, Netherlands, Nordics, etc.)'),
      opt('Europe - East (Poland, Romania, Balkans, Baltics, etc.)'),
      opt('Asia-Pacific - East (Japan, South Korea, Taiwan, etc.)'),
      opt('Asia-Pacific - Southeast (Singapore, Australia, India, etc.)'),
      opt('Middle East / Africa'),
      opt('Other'),
    ],
  },
  {
    id: 'q2',
    section: 1,
    sectionTitle: 'Questions about your Immich server, your library and your internet speed',
    text: "What is your server's download speed?",
    type: 'radio',
    required: true,
    options: [
      opt('Less than 10Mbps'),
      opt('10 - 25Mbps'),
      opt('26 - 50Mbps'),
      opt('51 - 100Mbps'),
      opt('101 - 500Mbps'),
      opt('501 - 1Gbps'),
      opt('Over 1Gbps'),
      opt("I'm not sure"),
    ],
  },
  {
    id: 'q3',
    section: 1,
    sectionTitle: 'Questions about your Immich server, your library and your internet speed',
    text: "What is your server's upload speed?",
    type: 'radio',
    required: true,
    options: [
      opt('Less than 10Mbps'),
      opt('10 - 25Mbps'),
      opt('26 - 50Mbps'),
      opt('51 - 100Mbps'),
      opt('101 - 500Mbps'),
      opt('501 - 1Gbps'),
      opt('Over 1Gbps'),
      opt("I'm not sure"),
    ],
  },
  {
    id: 'q4',
    section: 1,
    sectionTitle: 'Questions about your Immich server, your library and your internet speed',
    text: 'What is the total size of your Immich library?',
    description: 'You can find this on your <a href="https://my.immich.app/admin/server-status" target="_blank" rel="noopener noreferrer" class="underline text-immich-primary">server status page</a>.',
    type: 'radio',
    required: true,
    options: [
      opt('Less than 100GB'),
      opt('100GB - 250GB'),
      opt('250GB - 500GB'),
      opt('500GB - 1TB'),
      opt('1 - 5TB'),
      opt('5 - 10TB'),
      opt('10 - 50TB'),
      opt('50TB+'),
    ],
  },
  {
    id: 'q5',
    section: 1,
    sectionTitle: 'Questions about your Immich server, your library and your internet speed',
    text: 'Roughly what percentage of your library by storage used is video?',
    description:
      'Example: If you have 600GB of photos & videos combined and 500GB of that is videos, select 80%.',
    type: 'radio',
    required: true,
    options: [
      opt('Almost none (less than 10%)'),
      opt('A small portion (10 - 25%)'),
      opt('A significant chunk (25 - 50%)'),
      opt('Mostly video (50 - 75%)'),
      opt('Almost entirely video (75%+)'),
      opt("I'm not sure"),
    ],
  },
  {
    id: 'q6',
    section: 1,
    sectionTitle: 'Questions about your Immich server, your library and your internet speed',
    text: 'How would you describe your self-hosting experience?',
    type: 'radio',
    required: true,
    options: [
      opt('Novice - Immich is the first and only service I run and I followed a guide to do that'),
      opt('Beginner - I have a few self-hosted services running but that is it'),
      opt("Intermediate - I'm comfortable with Docker, basic networking, and Linux"),
      opt('Advanced - I manage multiple services, custom configs, and infrastructure'),
      opt('Expert - I work in IT/infrastructure professionally or have deep sysadmin experience'),
    ],
  },

  // Section 2: Your current backup solution
  {
    id: 'q7',
    section: 2,
    sectionTitle: 'Three questions about your current backup methodology',
    text: 'How do you currently back up your Immich data?',
    type: 'radio',
    required: true,
    hasOther: true,
    otherPrompt: 'Please enter how you currently back up your Immich instance',
    options: [
      opt("I don't currently have a backup"),
      opt('RAID (but no offsite/separate copy)'),
      opt('ZFS snapshots / replication'),
      opt('Restic / Borg / Kopia or similar de-duplicating backup tool'),
      opt('Syncthing / rsync to another machine'),
      opt('Cloud sync (e.g. rclone to R2, S3, Backblaze B2, etc.)'),
      opt('Manual / ad-hoc copies'),
      opt('Other'),
    ],
  },
  {
    id: 'q8',
    section: 2,
    sectionTitle: 'Three questions about your current backup methodology',
    text: 'How often do you run backups?',
    type: 'radio',
    required: true,
    options: [
      opt('Continuously / real-time'),
      opt('Daily'),
      opt('Weekly'),
      opt('Monthly'),
      opt('Less than monthly'),
      opt("I don't have automated backups"),
    ],
  },
  {
    id: 'q9',
    section: 2,
    sectionTitle: 'Three questions about your current backup methodology',
    text: 'Roughly how much new data do you add to your Immich library in a typical month?',
    type: 'radio',
    required: true,
    options: [
      opt('Less than 1GB'),
      opt('1 - 10GB'),
      opt('10 - 50GB'),
      opt('50 - 100GB'),
      opt('100 - 500GB'),
      opt('Over 500GB'),
    ],
  },

  // Section 3: Questions about FUTO Backups - and your interest in it
  {
    id: 'q10',
    section: 3,
    sectionTitle: 'The Backup Service',
    text: 'How interested are you in a service like this?',
    type: 'radio',
    required: true,
    options: [
      opt('Very interested'),
      opt('Interested'),
      opt('Undecided / Need more details'),
      opt('Not interested'),
    ],
  },
  {
    id: 'q11',
    section: 3,
    sectionTitle: 'The Backup Service',
    text: 'How much would you be willing to pay per TB per month for this service?',
    type: 'radio',
    required: true,
    options: [
      opt('$3.99/TB/Month'),
      opt('$4.99/TB/Month'),
      opt('$5.99/TB/Month'),
      opt('$6.99/TB/Month'),
      opt('$7.99/TB/Month'),
      opt('$8.99/TB/Month'),
      opt('$9.99/TB/Month'),
      opt("I wouldn't pay for this"),
    ],
  },
  {
    id: 'q12',
    section: 3,
    sectionTitle: 'The Backup Service',
    text: 'How many copies of your backup would you want stored in the cloud?',
    description:
      'Each additional copy is stored in a separate location for extra redundancy and will cost extra',
    type: 'radio',
    required: true,
    options: [
      opt('1 copy'),
      opt('2 copies'),
      opt('3 copies'),
      opt('4+ copies'),
      opt("I'm not sure / It depends on the cost"),
    ],
  },

  // Section 4: Private Beta Signup
  {
    id: 'q17',
    section: 4,
    sectionTitle: 'Beta Program',
    text: 'Stay in the loop',
    description:
      "As we've explained, we're working on FUTO Backups so that you can securely backup your Immich library. The closed beta will be completely free. You can sign up here if you'd like, but this is totally optional.",
    type: 'email-signup',
    required: false,
    placeholder: 'name@example.com',
    options: [
      opt('Join the closed beta'),
      opt('Receive product updates'),
    ],
  },

  // Section 5: Additional questions about how you host Immich
  {
    id: 'q13',
    section: 5,
    sectionTitle: 'Additional questions about your Immich instance',
    text: 'What type of storage does your Immich server use for its media library?',
    type: 'radio',
    required: true,
    hasOther: true,
    otherPrompt: 'Please enter what type of storage does your Immich server use for its media library',
    options: [
      opt('Directly attached storage'),
      opt('Network attached storage'),
      opt('Cloud/object storage (e.g. S3/MinIO)'),
      opt('Other'),
    ],
  },
  {
    id: 'q14',
    section: 5,
    sectionTitle: 'Additional questions about your Immich instance',
    text: 'What type of drives primarily make up your media storage?',
    type: 'radio',
    required: true,
    hasOther: true,
    otherPrompt: 'Please enter what type of drives primarily make up your media storage',
    options: [opt('NVMe SSD'), opt('SATA SSD'), opt('HDD (spinning disk)'), opt('Other')],
  },
  {
    id: 'q15',
    section: 5,
    sectionTitle: 'Additional questions about your Immich instance',
    text: 'What is the underlying OS or Hypervisor running your Immich server?',
    type: 'radio',
    required: true,
    hasOther: true,
    otherPrompt: 'Please enter the underlying OS or Hypervisor running your Immich server',
    options: [
      opt('Bare metal Linux (Ubuntu, Debian, etc.)'),
      opt('Proxmox VE'),
      opt('TrueNAS / FreeNAS'),
      opt('Unraid'),
      opt('Windows / MacOS'),
      opt('NixOS'),
      opt('Umbrel'),
      opt('ZimaOS'),
      opt('HexOS'),
      opt('Other'),
    ],
  },
  {
    id: 'q16',
    section: 5,
    sectionTitle: 'Additional questions about your Immich instance',
    text: 'How are you running Immich?',
    type: 'radio',
    required: true,
    hasOther: true,
    otherPrompt: 'Please enter how you are running Immich',
    options: [
      opt('Docker / Docker Compose'),
      opt('Kubernetes'),
      opt('LXC / System Container'),
      opt('Nix'),
      opt('Unraid App'),
      opt('TrueNAS App / Chart'),
      opt('Other'),
    ],
  },

  // Section 6: Final thoughts
  {
    id: 'q19',
    section: 6,
    sectionTitle: 'Final Thoughts',
    text: 'Is there anything else you\'d like to share?',
    description:
      "Any thoughts, concerns, features you'd want, or questions about a managed backup service for Immich",
    type: 'textarea',
    required: false,
    maxLength: 5000,
  },
];

export const sections: SurveySection[] = [
  {
    number: 1,
    title: 'Questions about your Immich server, your library and your internet speed',
    questionIds: ['q1', 'q2', 'q3', 'q4', 'q5', 'q6'],
  },
  {
    number: 2,
    title: 'Three questions about your current backup methodology',
    description:
      "We'd like to know how many of your precious memories are at risk of going 💨",
    questionIds: ['q7', 'q8', 'q9'],
  },
  {
    number: 3,
    title: 'The Backup Service',
    description:
      "We're building a managed backup service that integrates directly into Immich. Your library would be backed up to a remote datacentre with end-to-end encryption, meaning only you hold the keys to your data. The idea is for this service to be extremely simple to setup and should include all kinds of things that usually you need to setup yourself. e.g. Alerting on failed backups, automated restore tests, integrity checks and more.",
    questionIds: ['q10', 'q11', 'q12'],
  },
  {
    number: 4,
    title: 'Beta Program',
    description:
      "We're planning a closed beta before the full launch. If you'd like early access or product updates, leave your email on the next screen.",
    questionIds: ['q17'],
  },
  {
    number: 5,
    title: 'Additional questions about your Immich instance',
    description:
      "We have further questions when it comes to your Immich instance. Your answers will allow us to better tailor Immich's development in the future.",
    questionIds: ['q13', 'q14', 'q15', 'q16'],
  },
  {
    number: 6,
    title: 'Final Thoughts',
    questionIds: ['q19'],
  },
];
