export enum ChildKey {
  Field = 'field',
  HelperText = 'helped-text',
  AppShell = 'app-shell',
  AppShellHeader = 'app-shell-header',
  AppShellBar = 'app-shell-bar',
  AppShellSidebar = 'app-shell-sidebar',
  Card = 'card',
  CardHeader = 'card-header',
  CardBody = 'card-body',
  CardFooter = 'card-footer',
  ControlBar = 'control-bar',
  ControlBarHeader = 'control-bar-header',
  ControlBarContent = 'control-bar-content',
  ControlBarOverflow = 'control-bar-overflow',
  Modal = 'modal',
  ModalHeader = 'modal-header',
  ModalBody = 'modal-body',
  ModalFooter = 'modal-footer',
  Table = 'table',
  TableHeader = 'table-header',
  TableBody = 'table-body',
  TableFooter = 'table-footer',
}

export const zIndex = {
  CarouselImage: 'z-1',
  AppShellSidebar: 'z-30',
  AppShellBar: 'z-35',
  ModalBackdrop: 'z-40',
  ModalContent: 'z-50',
  SelectDropdown: 'z-55',
  ToastPanel: 'z-60',
  ContextMenu: 'z-70!',
  Tooltip: 'z-90',
  ScreencastOverlay: 'z-10000',
};
