packages:
  - apps/*
  - apps/*/backend
  - packages/*

dedupePeerDependents: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd

preferWorkspacePackages: true

shamefullyHoist: false

verifyDepsBeforeRun: install
