packages:
  - apps/*
  - apps/*/backend
  - packages/*

dedupePeerDependents: true

allowBuilds:
  '@tailwindcss/oxide': true
  better-sqlite3: true
  core-js: false
  cpu-features: false
  esbuild: true
  exifreader: false
  protobufjs: false
  sharp: true
  ssh2: false
  workerd: true

preferWorkspacePackages: true

shamefullyHoist: false

verifyDepsBeforeRun: install

overrides:
  svelte-highlight: 7.20.0
