packages:
  - apps/*
  - apps/*/backend
  - packages/*

dedupePeerDependents: true

ignoredOptionalDependencies:
  - canvas
  - jsdom

allowBuilds:
  '@tailwindcss/oxide': true
  cpu-features: false
  esbuild: true
  exifreader: false
  protobufjs: false
  sharp: true
  ssh2: false
  workerd: true

preferWorkspacePackages: true

shamefullyHoist: false

verifyDepsBeforeRun: install
