<script lang="ts">
  import { siteMetadata } from '$lib';
  import Timeline from '$lib/components/Timeline.svelte';
  import type { TimelineItem } from '$lib/types';
  import { Heading, SiteMetadata, Stack, Text } from '@immich/ui';
  import {
    mdiAccountGroup,
    mdiAccountGroupOutline,
    mdiAndroid,
    mdiApi,
    mdiAppleIos,
    mdiArchiveOutline,
    mdiBash,
    mdiBookmark,
    mdiBookSearchOutline,
    mdiCakeVariant,
    mdiCameraBurst,
    mdiCast,
    mdiChartBoxMultipleOutline,
    mdiCheckAll,
    mdiCheckboxMarked,
    mdiCloudUploadOutline,
    mdiCollage,
    mdiContentDuplicate,
    mdiCrop,
    mdiDatabaseOutline,
    mdiDevices,
    mdiDisc,
    mdiEmailOutline,
    mdiExpansionCard,
    mdiEyeOutline,
    mdiEyeRefreshOutline,
    mdiFaceMan,
    mdiFaceManOutline,
    mdiFaceRecognition,
    mdiFile,
    mdiFileSearch,
    mdiFlash,
    mdiFolder,
    mdiFolderMultiple,
    mdiFolderSync,
    mdiForum,
    mdiHandshakeOutline,
    mdiHeart,
    mdiHistory,
    mdiImage,
    mdiImageAlbum,
    mdiImageEdit,
    mdiImageMultipleOutline,
    mdiImagePlusOutline,
    mdiImageSearch,
    mdiKeyboardSettingsOutline,
    mdiLicense,
    mdiLinkEdit,
    mdiLockOutline,
    mdiMagnify,
    mdiMagnifyScan,
    mdiMap,
    mdiMaterialDesign,
    mdiMatrix,
    mdiMerge,
    mdiMonitor,
    mdiMotionPlayOutline,
    mdiMovieOpenPlayOutline,
    mdiOcr,
    mdiPalette,
    mdiPanVertical,
    mdiPartyPopper,
    mdiPencil,
    mdiRaw,
    mdiRocketLaunch,
    mdiRotate360,
    mdiRotateLeft,
    mdiScaleBalance,
    mdiSecurity,
    mdiServer,
    mdiShare,
    mdiShareAll,
    mdiShareCircle,
    mdiStar,
    mdiStarOutline,
    mdiTableKey,
    mdiTag,
    mdiTagFaces,
    mdiTagMultiple,
    mdiText,
    mdiThemeLightDark,
    mdiTrashCanOutline,
    mdiUploadMultipleOutline,
    mdiVectorCombine,
    mdiVideo,
    mdiWeb,
  } from '@mdi/js';

  const releases = {
    'v2.0.0': new Date(2025, 9, 1),
    'v1.141.1': new Date(2025, 8, 8),
    'v1.135.0': new Date(2025, 5, 18),
    'v1.133.0': new Date(2025, 4, 21),
    'v1.130.0': new Date(2025, 2, 25),
    'v1.127.0': new Date(2025, 1, 26),
    'v1.122.0': new Date(2024, 11, 5),
    'v1.120.0': new Date(2024, 10, 6),
    'v1.114.0': new Date(2024, 8, 6),
    'v1.113.0': new Date(2024, 7, 30),
    'v1.112.0': new Date(2024, 7, 14),
    'v1.111.0': new Date(2024, 6, 26),
    'v1.110.0': new Date(2024, 5, 11),
    'v1.109.0': new Date(2024, 6, 18),
    'v1.106.1': new Date(2024, 5, 11),
    'v1.104.0': new Date(2024, 4, 13),
    'v1.103.0': new Date(2024, 3, 29),
    'v1.102.0': new Date(2024, 3, 15),
    'v1.99.0': new Date(2024, 2, 20),
    'v1.98.0': new Date(2024, 2, 7),
    'v1.95.0': new Date(2024, 1, 20),
    'v1.94.0': new Date(2024, 0, 31),
    'v1.93.0': new Date(2024, 0, 19),
    'v1.91.0': new Date(2023, 11, 15),
    'v1.90.0': new Date(2023, 11, 7),
    'v1.88.0': new Date(2023, 10, 20),
    'v1.84.0': new Date(2023, 10, 1),
    'v1.83.0': new Date(2023, 9, 28),
    'v1.82.0': new Date(2023, 9, 17),
    'v1.79.0': new Date(2023, 8, 21),
    'v1.76.0': new Date(2023, 7, 29),
    'v1.75.0': new Date(2023, 7, 26),
    'v1.72.0': new Date(2023, 7, 6),
    'v1.71.0': new Date(2023, 6, 29),
    'v1.69.0': new Date(2023, 6, 23),
    'v1.68.0': new Date(2023, 6, 20),
    'v1.67.0': new Date(2023, 6, 14),
    'v1.66.0': new Date(2023, 6, 4),
    'v1.65.0': new Date(2023, 5, 30),
    'v1.63.0': new Date(2023, 5, 24),
    'v1.61.0': new Date(2023, 5, 16),
    'v1.58.0': new Date(2023, 4, 28),
    'v1.57.0': new Date(2023, 4, 23),
    'v1.56.0': new Date(2023, 4, 18),
    'v1.55.0': new Date(2023, 4, 9),
    'v1.54.0': new Date(2023, 3, 18),
    'v1.52.0': new Date(2023, 2, 29),
    'v1.51.0': new Date(2023, 2, 20),
    'v1.48.0': new Date(2023, 1, 21),
    'v1.47.0': new Date(2023, 1, 13),
    'v1.46.0': new Date(2023, 1, 9),
    'v1.43.0': new Date(2023, 1, 3),
    'v1.41.0': new Date(2023, 0, 10),
    'v1.39.0': new Date(2022, 11, 19),
    'v1.36.0': new Date(2022, 10, 20),
    'v1.33.1': new Date(2022, 9, 26),
    'v1.32.0': new Date(2022, 9, 14),
    'v1.27.0': new Date(2022, 8, 6),
    'v1.24.0': new Date(2022, 7, 19),
    'v1.10.0': new Date(2022, 4, 29),
    'v1.7.0': new Date(2022, 3, 24),
    'v1.3.0': new Date(2022, 2, 22),
    'v1.2.0': new Date(2022, 1, 8),
  } as const;

  const weirdTags = {
    'v1.41.0': 'v1.41.1_64-dev',
    'v1.39.0': 'v1.39.0_61-dev',
    'v1.36.0': 'v1.36.0_55-dev',
    'v1.33.1': 'v1.33.0_52-dev',
    'v1.32.0': 'v1.32.0_50-dev',
    'v1.27.0': 'v1.27.0_37-dev',
    'v1.24.0': 'v1.24.0_34-dev',
    'v1.10.0': 'v1.10.0_15-dev',
    'v1.7.0': 'v1.7.0_11-dev ',
    'v1.3.0': 'v1.3.0-dev ',
    'v1.2.0': 'v0.2-dev ',
  };

  type ReleaseVersion = keyof typeof releases | keyof typeof weirdTags;

  const withLanguage = (date: Date) => (language: string) => date.toLocaleDateString(language);

  type Base = {
    icon: string;
    title: string;
    description: string;
  };
  const releaseItem = ({ icon, title, description, release: version }: Base & { release: ReleaseVersion }) => {
    return {
      icon,
      title,
      description,
      link: {
        url: `https://github.com/immich-app/immich/releases/tag/${weirdTags[version as keyof typeof weirdTags] ?? version}`,
        text: version,
      },
      getDateLabel: withLanguage(releases[version]),
    };
  };

  const starMilestone = (count: number, date: Date) => ({
    icon: mdiStar,
    iconClass: 'text-warning',
    title: `${count.toLocaleString()} Stars`,
    description: `Reached ${count / 1000}K Stars on GitHub!`,
    getDateLabel: withLanguage(date),
  });

  const roadmap: TimelineItem[] = [
    {
      icon: mdiShareAll,
      title: 'Better sharing',
      description: 'Improve sharing capabilities, especially around facial recognition data',
    },
    {
      icon: mdiAccountGroupOutline,
      title: 'User groups',
      description: 'Manage groups of users and share albums with a group',
    },
    {
      icon: mdiFlash,
      title: 'Workflows',
      description: 'Automate tasks with workflows',
    },
    {
      icon: mdiImageEdit,
      title: 'Basic editor',
      description: 'Basic photo editing capabilities',
    },
    {
      icon: mdiRotateLeft,
      title: 'Rotation',
      description: 'Rotate an image 90, 180, or 270 degrees',
    },
    {
      icon: mdiUploadMultipleOutline,
      title: 'Chunked uploads',
      description: 'Upload large files in smaller chunks to improve reliability',
    },
    {
      icon: mdiOcr,
      title: 'Optical character recognition (OCR)',
      description: 'Use machine learning to extract text from images and make it searchable',
    },
    {
      icon: mdiCameraBurst,
      title: 'Automatic stacking',
      description: 'Automatically stack burst photos',
    },
    {
      icon: mdiImagePlusOutline,
      title: 'Smart albums',
      description: 'Automatically create albums based on rules',
    },
  ].map((item) => ({
    ...item,
    done: false,
    iconClass: 'text-muted',
    getDateLabel: () => 'Soon™',
  }));

  const milestones: TimelineItem[] = [
    starMilestone(80_000, new Date(2025, 9, 5)),
    releaseItem({
      icon: mdiDisc,
      title: 'Retro DVD & stealth merch',
      description:
        'Launched a demo DVD that comes pre-installed with Immich v2, as well as a new lineup of stealth merch',
      release: 'v2.0.0',
    }),
    releaseItem({
      icon: mdiApi,
      title: 'New API documentation',
      description: 'Launched a dedicated website for API documentation: https://api.immich.app/',
      release: 'v2.0.0',
    }),
    releaseItem({
      icon: mdiWeb,
      title: 'New homepage',
      description: 'Launched a new version of our website: https://immich.app/',
      release: 'v2.0.0',
    }),
    releaseItem({
      icon: mdiRocketLaunch,
      title: 'Stable release',
      description: 'Immich goes stable with v2.0.0',
      release: 'v2.0.0',
    }),
    releaseItem({
      icon: mdiCloudUploadOutline,
      title: 'Better background backups',
      description: 'Rework background backups to be more reliable',
      release: 'v1.141.1',
    }),
    starMilestone(70000, new Date(2025, 6, 9)),
    releaseItem({
      icon: mdiTableKey,
      title: 'Fine grained access controls',
      description: 'Granular access controls for api keys',
      release: 'v1.135.0',
    }),
    releaseItem({
      icon: mdiCast,
      title: 'Google Cast (web and mobile)',
      description: 'Cast assets to Google Cast/Chromecast compatible devices',
      release: 'v1.135.0',
    }),
    releaseItem({
      icon: mdiLockOutline,
      title: 'Private/locked photos',
      description: 'Private assets with extra protections',
      release: 'v1.133.0',
    }),
    releaseItem({
      icon: mdiFolderMultiple,
      title: 'Folders view in the mobile app',
      description: 'Browse your photos and videos in their folder structure inside the mobile app',
      release: 'v1.130.0',
    }),
    starMilestone(60000, new Date(2025, 2, 4)),
    releaseItem({
      icon: mdiTagFaces,
      title: 'Manual face tagging',
      description:
        'Manually tag or remove faces in photos and videos, even when automatic detection misses or misidentifies them.',
      release: 'v1.127.0',
    }),
    releaseItem({
      icon: mdiLinkEdit,
      title: 'Automatic URL switching',
      description: 'The mobile app now supports automatic switching between different server URLs',
      release: 'v1.122.0',
    }),
    releaseItem({
      icon: mdiMovieOpenPlayOutline,
      title: 'Native video player',
      description: 'HDR videos are now fully supported using the Immich native video player',
      release: 'v1.122.0',
    }),
    releaseItem({
      icon: mdiDatabaseOutline,
      title: 'Automatic database dumps',
      description: 'Database dumps are now integrated into the Immich server',
      release: 'v1.120.0',
    }),
    starMilestone(50000, new Date(2024, 10, 1)),
    releaseItem({
      icon: mdiFaceRecognition,
      title: 'Metadata Face Import',
      description: 'Read face metadata in Digikam format during import',
      release: 'v1.114.0',
    }),
    releaseItem({
      icon: mdiTagMultiple,
      title: 'Tags',
      description: 'Tag your photos and videos',
      release: 'v1.113.0',
    }),
    releaseItem({
      icon: mdiFolderSync,
      title: 'Album sync (mobile)',
      description: 'Sync or mirror an album from your phone to the Immich server',
      release: 'v1.113.0',
    }),
    releaseItem({
      icon: mdiFolderMultiple,
      title: 'Folders view',
      description: 'Browse your photos and videos in their folder structure',
      release: 'v1.113.0',
    }),
    releaseItem({
      icon: mdiPalette,
      title: 'Theming (mobile)',
      description: 'Pick a primary color for the mobile app',
      release: 'v1.112.0',
    }),
    releaseItem({
      icon: mdiStarOutline,
      title: 'Star rating',
      description: 'Rate your photos and videos',
      release: 'v1.112.0',
    }),
    releaseItem({
      icon: mdiCrop,
      title: 'Editor (mobile)',
      description: 'Crop and rotate on mobile',
      release: 'v1.111.0',
    }),
    releaseItem({
      icon: mdiMap,
      title: 'Deploy tiles.immich.cloud',
      description: 'Dedicated tile server for Immich',
      release: 'v1.111.0',
    }),
    starMilestone(40000, new Date(2024, 6, 21)),
    releaseItem({
      icon: mdiShare,
      title: 'Deploy my.immich.app',
      description: 'Url router for immich links',
      release: 'v1.109.0',
    }),
    releaseItem({
      icon: mdiLicense,
      title: 'Supporter Badge',
      description: 'The option to buy Immich to support its development!',
      release: 'v1.109.0',
    }),
    releaseItem({
      icon: mdiHistory,
      title: 'Versioned documentation',
      description: 'View documentation as it was at the time of past releases',
      release: 'v1.106.1',
    }),
    releaseItem({
      icon: mdiWeb,
      title: 'Web translations',
      description: 'Translate the web application to multiple languages',
      release: 'v1.106.1',
    }),
    releaseItem({
      icon: mdiContentDuplicate,
      title: 'Similar image detection',
      description: "Detect duplicate assets that aren't exactly identical",
      release: 'v1.106.1',
    }),
    releaseItem({
      icon: mdiVectorCombine,
      title: 'Container consolidation',
      description:
        'The microservices container can be run as a worker within the server image, allowing us to remove it from the default stack.',
      release: 'v1.106.1',
    }),
    releaseItem({
      icon: mdiPencil,
      title: 'Read-write external libraries',
      description: 'Edit, update, and delete files in external libraries',
      release: 'v1.104.0',
    }),
    releaseItem({
      icon: mdiEmailOutline,
      title: 'Email notifications',
      description: 'Send emails for important events',
      release: 'v1.104.0',
    }),
    {
      icon: mdiHandshakeOutline,
      title: 'Immich joins FUTO!',
      description: 'Joined Futo and Immich core team goes full-time',
      getDateLabel: withLanguage(new Date(2024, 4, 1)),
    },
    releaseItem({
      icon: mdiEyeOutline,
      title: 'Read-only albums',
      description: 'Share albums with other users as read-only',
      release: 'v1.103.0',
    }),
    releaseItem({
      icon: mdiBookmark,
      title: 'Permanent URLs (Web)',
      description: 'Assets on the web now have permanent URLs',
      release: 'v1.103.0',
    }),
    starMilestone(30000, new Date(2024, 2, 20)),
    releaseItem({
      icon: mdiChartBoxMultipleOutline,
      title: 'OpenTelemetry metrics',
      description: 'OpenTelemetry metrics for local evaluation and advanced debugging',
      release: 'v1.99.0',
    }),
    releaseItem({
      icon: 'immich',
      title: 'New logo',
      description: 'Immich got its new logo',
      release: 'v1.98.0',
    }),
    releaseItem({
      icon: mdiMagnifyScan,
      title: 'Search enhancement with advanced filters',
      description: 'Advanced search with filters by date, location and more',
      release: 'v1.95.0',
    }),
    releaseItem({
      icon: mdiScaleBalance,
      title: 'AGPL License',
      description: 'Immich switches to AGPLv3 license',
      release: 'v1.95.0',
    }),
    releaseItem({
      icon: mdiEyeRefreshOutline,
      title: 'Library watching',
      description: 'Automatically import files in external libraries when the operating system detects changes.',
      release: 'v1.94.0',
    }),
    releaseItem({
      icon: mdiExpansionCard,
      title: 'GPU acceleration for machine-learning',
      description: 'Hardware acceleration support for Nvidia and Intel devices through CUDA and OpenVINO.',
      release: 'v1.94.0',
    }),
    releaseItem({
      icon: mdiAccountGroupOutline,
      title: '250 unique contributors',
      description: '250 amazing people contributed to Immich',
      release: 'v1.93.0',
    }),
    releaseItem({
      icon: mdiMatrix,
      title: 'Search improvement with pgvecto.rs',
      description: 'Moved the search from typesense to pgvecto.rs',
      release: 'v1.91.0',
    }),
    releaseItem({
      icon: mdiPencil,
      title: 'Edit metadata',
      description: "Edit a photo or video's date, time, hours, timezone, and GPS information",
      release: 'v1.90.0',
    }),
    releaseItem({
      icon: mdiVectorCombine,
      title: 'Container consolidation',
      description:
        'The serving of the web app is merged into the server image, allowing us to remove two containers from the stack.',
      release: 'v1.88.0',
    }),
    releaseItem({
      icon: mdiBash,
      title: 'CLI v2',
      description: 'Version 2 of the Immich CLI is released, replacing the legacy v1 CLI.',
      release: 'v1.88.0',
    }),
    releaseItem({
      icon: mdiForum,
      title: 'Activity',
      description: 'Comment a photo or a video in a shared album',
      release: 'v1.84.0',
    }),
    starMilestone(20000, new Date(2023, 9, 28)),
    releaseItem({
      icon: mdiCameraBurst,
      title: 'Stack assets',
      description: 'Manual asset stacking for grouping and hiding related assets in the main timeline.',
      release: 'v1.83.0',
    }),
    releaseItem({
      icon: mdiPalette,
      title: 'Custom theme',
      description: 'Apply your custom CSS for modifying fonts, colors, and styles in the web application.',
      release: 'v1.83.0',
    }),
    releaseItem({
      icon: mdiTrashCanOutline,
      title: 'Trash feature',
      description: 'Trash, restore from trash, and automatically empty the recycle bin after 30 days.',
      release: 'v1.82.0',
    }),
    releaseItem({
      icon: mdiBookSearchOutline,
      title: 'External libraries',
      description: 'Automatically import media into Immich based on imports paths and ignore patterns.',
      release: 'v1.79.0',
    }),
    releaseItem({
      icon: mdiMap,
      title: 'Map view (mobile)',
      description: 'Heat map implementation in the mobile app.',
      release: 'v1.76.0',
    }),
    releaseItem({
      icon: mdiFile,
      title: 'Configuration file',
      description: 'Auto-configure an Immich installation via a configuration file.',
      release: 'v1.75.0',
    }),
    releaseItem({
      icon: mdiMonitor,
      title: 'Slideshow mode (web)',
      description: 'Start a full-screen slideshow from an Album on the web.',
      release: 'v1.75.0',
    }),
    releaseItem({
      icon: mdiServer,
      title: 'Hardware transcoding',
      description: 'Support hardware acceleration (QuickSync, VAAPI, and Nvidia) for video transcoding.',
      release: 'v1.72.0',
    }),
    releaseItem({
      icon: mdiImageAlbum,
      title: 'View albums via time buckets',
      description: 'Upgrade albums to use time buckets, an optimized virtual viewport.',
      release: 'v1.72.0',
    }),
    releaseItem({
      icon: mdiImageAlbum,
      title: 'Album description',
      description: 'Save an album description.',
      release: 'v1.72.0',
    }),
    releaseItem({
      icon: mdiRotate360,
      title: '360° Photos (web)',
      description: 'View 360° Photos on the web.',
      release: 'v1.71.0',
    }),
    releaseItem({
      icon: mdiMotionPlayOutline,
      title: 'Android motion photos',
      description: 'Add support for Android Motion Photos.',
      release: 'v1.69.0',
    }),
    releaseItem({
      icon: mdiFaceManOutline,
      title: 'Show/hide faces',
      description: 'Add the options to show or hide faces.',
      release: 'v1.68.0',
    }),
    releaseItem({
      icon: mdiMerge,
      title: 'Merge faces',
      description: 'Add the ability to merge multiple faces together.',
      release: 'v1.67.0',
    }),
    releaseItem({
      icon: mdiImage,
      title: 'Feature photo',
      description: 'Add the option to change the feature photo for a person.',
      release: 'v1.66.0',
    }),
    releaseItem({
      icon: mdiKeyboardSettingsOutline,
      title: 'Multi-select via SHIFT',
      description: 'Add the option to multi-select while holding SHIFT.',
      release: 'v1.66.0',
    }),
    releaseItem({
      icon: mdiImageMultipleOutline,
      title: 'Memories (mobile)',
      description: 'View "On this day..." memories in the mobile app.',
      release: 'v1.65.0',
    }),
    releaseItem({
      icon: mdiFaceMan,
      title: 'Facial recognition (mobile)',
      description: 'View detected faces in the mobile app.',
      release: 'v1.63.0',
    }),
    releaseItem({
      icon: mdiImageMultipleOutline,
      title: 'Memories (web)',
      description: 'View pictures taken in past years on this day on the web.',
      release: 'v1.61.0',
    }),
    releaseItem({
      icon: mdiCollage,
      title: 'Justified layout (web)',
      description: 'Implement justified layout (collage) on the web.',
      release: 'v1.61.0',
    }),
    releaseItem({
      icon: mdiRaw,
      title: 'RAW file formats',
      description: 'Support for RAW file formats.',
      release: 'v1.61.0',
    }),
    releaseItem({
      icon: mdiShareAll,
      title: 'Partner sharing (mobile)',
      description: 'View shared partner photos in the mobile app.',
      release: 'v1.58.0',
    }),
    releaseItem({
      icon: mdiFile,
      title: 'XMP sidecar',
      description: 'Attach XMP sidecar files to assets.',
      release: 'v1.58.0',
    }),
    releaseItem({
      icon: mdiFolder,
      title: 'Custom storage label',
      description: 'Replace the user UUID in the storage template with a custom label.',
      release: 'v1.57.0',
    }),
    releaseItem({
      icon: mdiShareCircle,
      title: 'Partner sharing',
      description: 'Share your entire collection with another user.',
      release: 'v1.56.0',
    }),
    releaseItem({
      icon: mdiFaceMan,
      title: 'Facial recognition',
      description: 'Detect faces in pictures and cluster them together as people, which can be named.',
      release: 'v1.56.0',
    }),
    releaseItem({
      icon: mdiMap,
      title: 'Map view (web)',
      description: 'View a global map, with clusters of photos based on corresponding GPS data.',
      release: 'v1.55.0',
    }),
    releaseItem({
      icon: mdiDevices,
      title: 'Manage auth devices',
      description: 'Manage logged-in devices and revoke access from User Settings.',
      release: 'v1.55.0',
    }),
    starMilestone(10000, new Date(2023, 3, 18)),
    releaseItem({
      icon: mdiText,
      title: 'Asset descriptions',
      description: 'Save an asset description',
      release: 'v1.54.0',
    }),
    releaseItem({
      icon: mdiArchiveOutline,
      title: 'Archiving',
      description: 'Remove assets from the main timeline by archiving them.',
      release: 'v1.54.0',
    }),
    releaseItem({
      icon: mdiDevices,
      title: 'Responsive web app',
      description: 'Optimize the web app for small screen.',
      release: 'v1.54.0',
    }),
    releaseItem({
      icon: mdiFileSearch,
      title: 'Search by metadata',
      description: 'Search images by filename, description, tagged people, make, model, and other metadata.',
      release: 'v1.52.0',
    }),
    releaseItem({
      icon: mdiImageSearch,
      title: 'CLIP search',
      description: 'Search images with free-form text like "Sunset at the beach".',
      release: 'v1.51.0',
    }),
    releaseItem({
      icon: mdiMagnify,
      title: 'Explore page',
      description: 'View tagged places, object, and people.',
      release: 'v1.51.0',
    }),
    releaseItem({
      icon: mdiAppleIos,
      title: 'iOS background uploads',
      description: 'Automatically backup pictures in the background on iOS.',
      release: 'v1.48.0',
    }),
    releaseItem({
      icon: mdiMotionPlayOutline,
      title: 'Auto-Link live photos',
      description: 'Automatically link live photos, even when uploaded as separate files.',
      release: 'v1.48.0',
    }),
    releaseItem({
      icon: mdiMaterialDesign,
      title: 'Material design 3 (mobile)',
      description: 'Upgrade the mobile app to Material Design 3.',
      release: 'v1.47.0',
    }),
    releaseItem({
      icon: mdiHeart,
      title: 'Favorites (mobile)',
      description: 'Show favorites on the mobile app.',
      release: 'v1.46.0',
    }),
    releaseItem({
      icon: mdiCakeVariant,
      title: 'Immich turns 1',
      description: 'Immich is officially one year old.',
      release: 'v1.43.0',
    }),
    releaseItem({
      icon: mdiHeart,
      title: 'Favorites page (web)',
      description: 'Favorite and view favorites on the web.',
      release: 'v1.43.0',
    }),
    releaseItem({
      icon: mdiShareCircle,
      title: 'Public share links',
      description: 'Share photos and albums publicly via a shared link.',
      release: 'v1.41.0',
    }),
    releaseItem({
      icon: mdiFolder,
      title: 'User-defined storage structure',
      description: 'Support custom storage structures.',
      release: 'v1.39.0',
    }),
    releaseItem({
      icon: mdiMotionPlayOutline,
      title: 'iOS live photos',
      description: 'Backup and display iOS Live Photos.',
      release: 'v1.36.0',
    }),
    releaseItem({
      icon: mdiSecurity,
      title: 'OAuth integration',
      description: 'Support OAuth2 and OIDC capable identity providers.',
      release: 'v1.36.0',
    }),
    releaseItem({
      icon: mdiWeb,
      title: 'Documentation site',
      description: 'Release an official documentation website.',
      release: 'v1.33.1',
    }),
    releaseItem({
      icon: mdiThemeLightDark,
      title: 'Dark mode (web)',
      description: 'Dark mode on the web.',
      release: 'v1.32.0',
    }),
    releaseItem({
      icon: mdiPanVertical,
      title: 'Virtual scrollbar (web)',
      description: 'View the main timeline with a virtual scrollbar, allowing to jump to any point in time, instantly.',
      release: 'v1.27.0',
    }),
    releaseItem({
      icon: mdiCheckAll,
      title: 'Checksum duplication check',
      description: 'Enforce per user sha1 checksum uniqueness.',
      release: 'v1.27.0',
    }),
    releaseItem({
      icon: mdiAndroid,
      title: 'Android background backup',
      description: 'Automatic backup in the background on Android.',
      release: 'v1.24.0',
    }),
    releaseItem({
      icon: mdiAccountGroup,
      title: 'Admin portal',
      description: 'Manage users and admin settings from the web.',
      release: 'v1.10.0',
    }),
    releaseItem({
      icon: mdiShareCircle,
      title: 'Album sharing',
      description: 'Share albums with other users.',
      release: 'v1.7.0',
    }),
    releaseItem({
      icon: mdiTag,
      title: 'Image tagging',
      description: 'Tag images with custom values.',
      release: 'v1.7.0',
    }),
    releaseItem({
      icon: mdiImage,
      title: 'View exif',
      description: 'View metadata about assets.',
      release: 'v1.3.0',
    }),
    releaseItem({
      icon: mdiCheckboxMarked,
      title: 'Multi select',
      description: 'Select and execute actions on multiple assets at the same time.',
      release: 'v1.2.0',
    }),
    releaseItem({
      icon: mdiVideo,
      title: 'Video player',
      description: 'Play videos in the web and on mobile.',
      release: 'v1.2.0',
    }),
    {
      icon: mdiPartyPopper,
      title: 'First commit',
      description: 'First commit on GitHub, Immich is born.',
      getDateLabel: withLanguage(new Date(2022, 1, 3)),
    },
  ];

  const pageMetadata = {
    title: 'Roadmap',
    description: 'A list of future plans and goals, as well as past achievements and milestones.',
  };
</script>

<SiteMetadata site={siteMetadata} page={pageMetadata} />

<Stack class="text-center" gap={4}>
  <Heading size="title" tag="h1">Roadmap</Heading>
  <Text>{pageMetadata.description}</Text>
</Stack>
<div class="flex justify-around mt-8 w-full max-w-(--breakpoint-md) mx-auto">
  <Timeline items={[...roadmap, ...milestones]} />
</div>
